colors

diff --git a/up b/up
--- a/up
+++ b/up
@@ -8,6 +8,12 @@
 #
 # ...And way we go!
 
+# Color variables 
+
+RED="\033[1;31m"
+GREEN="\033[1;32m"
+NOCOLOR="\033[0m"
+
 # Check for less utility and install if needed:
 
 dpkg -l | grep -qw less || sudo apt install less -yyq
@@ -20,7 +26,7 @@ set -e
 
 update() {
 
-echo "Starting full system update..."
+echo "${GREEN}Starting full system update...${NOCOLOR}"
 sudo apt update
 sudo apt full-upgrade -yy
 
@@ -28,14 +34,14 @@ sudo apt full-upgrade -yy
 
 clean() {
 
-echo "Removing apt cache packages that can no longer be downloaded..."
+echo "${GREEN}Removing apt cache packages that can no longer be downloaded...${NOCOLOR}"
 sudo apt autoclean
 
 }
 
 remove() {
 
-echo "Removing orpahned packages..."
+echo "${GREEN}Removing orpahned packages...${NOCOLOR}"
 sudo apt autoremove -yy
 sudo apt remove --purge $(dpkg -l | grep "^rc" | awk '{print $2}') -yy
 
@@ -43,9 +49,9 @@ sudo apt remove --purge $(dpkg -l | grep "^rc" | awk '{print $2}') -yy
 
 leave() {
 
-echo "--------------------"
-echo "- Update Complete! -"
-echo "--------------------"
+echo ${GREEN}"--------------------"${NOCOLOR}
+echo ${GREEN}"- Update Complete! -"${NOCOLOR}
+echo ${GREEN}"--------------------"${NOCOLOR}
 exit
 
 }
@@ -102,7 +108,7 @@ _EOF_
 
 # Tell 'em who we are...
 
-echo "Up -- Debian/Ubuntu Update Tool (Version 1.3)"
+echo "${GREEN}Up -- Debian/Ubuntu Update Tool (Version 1.3)${NOCOLOR}"
 
 # Update and clean:
 
@@ -129,9 +135,11 @@ fi
 # Check for invalid argument
 
 if  [ -n "$1"  ]; then
-    echo "Up Error: Invalid argument. Try 'up --help' for more info." >&2
+    echo "${RED}Up Error: Invalid argument.${NOCOLOR}\n ${GREEN}Try 'up --help' for more info.${NOCOLOR}" >&2
     exit 1
 fi
+
+# Call functions
 
 update
 leave
