Installer ready for release

diff --git a/upinst b/upinst
--- a/upinst
+++ b/upinst
@@ -13,16 +13,16 @@
 # ##################################################
 #
 # * 2019-04-12 - v0.0.0  - First Creation
+# * 2019-04-12 - v0.0.1  - creating the installer script
 #
 # ##################################################
 # Initializing constants and variables
 # ##################################################
 # Setting constants
-version="v0.0.0"            # Sets version variable
+version="v0.0.1"            # Sets version variable
 lastEdited="2019-04-12"     # Sets last edited variable" $scriptNamePath
 # Declaring variables
 # Declare all variables to be used in the script 
-declare destination          # Install destination
 declare sysop=0              # To check if SUDO is required
 declare linked=0             # To check if script is to be linked
 declare myPath=$(dirname $0) # Full path of upinst
@@ -71,8 +71,6 @@ if [ "$1" == "--help" ]; then
          option, and should only be used if you are using git clone 
          to download the update tool
 EOF
-    # Write information on arguments afterwards
-    # Write examples as required
     exit 0
 fi 
 # ##################################################
@@ -132,8 +130,8 @@ while [[ $1 = -?* ]]; do
   case $1 in
     # insert cases 
     # use shift; to catch arguments in $1
-    -a|--all) destination="/usr/local/bin"; sysop=1;;
-    -u|--user) destination="$HOME/bin"; sysop=0;;
+    -a|--all) sysop=1;;
+    -u|--user) sysop=0;;
     -l|--link) linked=1;;
     *) echo "ERROR: option $1 is not valid."; exit 1;; 
   esac
@@ -143,6 +141,103 @@ done
 # ##################################################
 # Main section
 # ##################################################
-# Write your script here
-echo $destination
-echo $sysop $linked
+echo "
+######################
+# Installing up - an update tool for Debian and Ubuntu based distros
+######################"
+# Check if install is to be systemwide
+if [ $sysop ]; then
+    echo "# up will be installed systemwide"
+    # then check if up is already installed
+    if [ -f "/usr/local/bin/up"]; then
+        # then update if repositiory is newer
+        echo "# up is previously installed"
+        sudo cp -u up /usr/local/bin
+        # check for error code
+        if [ $? ]; then
+            # then display error code and exit
+            echo "# up was not updated"
+            exit 1
+        else
+            # else display update message
+            echo "# up was updated successfully"
+        fi
+    else
+        # else copy up to /usr/local/bin
+        echo "# installing up in /usr/local/bin"
+        sudo cp up /usr/local/bin
+        # check for error code
+        if [ $? ]; then
+            # then display error code and exit
+            echo "# up was not installed"
+            exit 1
+        else
+            # else display install message
+            echo "# up was installed successfully"
+        fi
+    fi
+else
+    # else check if $HOME/bin does not exist
+    if [ ! -d "$HOME/bin" ]; then
+        echo "# $HOME/bin does not exist"
+        echo "# Creating $HOME/bin"
+        # create $HOME/bin
+        mkdir $HOME/bin
+        # check for error code
+        if [ $? ]; then
+            # then display error code and exit
+            echo "# couldn't create $HOME/bin"
+            exit 1
+        else
+            # else adding $HOME/bin to $PATH
+            echo "# adding $HOME/bin to \$PATH"
+            PATH="$HOME/bin:$PATH"
+        fi
+    fi
+    # check if up is to be linked
+    if [ $linked ]; then
+        # then create a link to repository in $HOME/bin
+        pushd $HOME/bin
+        ln $myPath/up
+        # check for error code
+        if [ $? ]; then
+            # then display error code and exit
+            echo "# couldn't link up to $myPath/up"
+            exit 1
+        else
+            # else displaying linked message
+            echo "# up successfully linked to $myPath/up"
+        fi
+        popd
+    else
+        # else check if up is already installed
+        if [ -f "$HOME/bin/up" ]; then
+            # then update if repository is newer
+            echo "# up is previously installed"
+            cp -u up $HOME/bin
+            # check for error code
+            if [ $? ]; then
+                # then display error code and exit
+                echo "# up was not updated"
+                exit 1
+            else
+                # else display update message
+                echo "# up was updated successfully"
+            fi
+        else
+            # else copy up to $HOME/bin
+            echo "# installing up in $HOME/bin"
+            cp up $HOME/bin
+            # check for error code
+            if [ $? ]; then
+                # then display error code and exit
+                echo "# up was not installed"
+                exit 1
+            else
+                # else display install message
+                echo "# up was installed successfully"
+            fi
+        fi
+    fi
+fi
+echo "######################"
